# Copyright (c) 2026 eric6227
# Released under the MIT License. See LICENSE file in the project root for full text.
mqtt_host: 192.168.2.45
mqtt_port: 1883
mqtt_topic: tank/telemetry/control
mqtt_monitor_topic: tank/telemetry/monitor
mqtt_username: ''
stream_url: http://192.168.2.188:81/stream
cam_resolution: 1280x720 (HD)
cam_quality: 20
cam_fps: 60
audio_port: 5004
stream_output_port: 8080
volume: 71
audio_enabled: true
control_key_forward: 16777235
control_key_backward: 16777237
control_key_left: 16777234
control_key_right: 16777236
control_key_boost: 66
control_key_shift_up: 81
control_key_shift_down: 65
control_key_mode_toggle: 77
control_max_output_pct: 70
control_boost_output_pct: 95
control_boost_max_ms: 15000
control_accel_rate_pct: 8
control_brake_strength_pct: 50
control_steering_factor: 0.4
control_steering_factor_high: 0.4
control_steering_factor_low: 0.4
control_steering_factor_reverse: 0.4
control_steering_factor_inplace: 0.4
control_reverse_steering_invert: true
control_wifi_cam_rssi_reconnect_threshold_dbm: -80.0
control_wifi_cam_rssi_reconnect_delay_ms: 1000
control_wifi_ctrl_rssi_reconnect_threshold_dbm: -80.0
control_wifi_ctrl_rssi_reconnect_delay_ms: 1000
control_upshift_threshold: 0.6
control_downshift_threshold: 0.25
control_shift_blip_pct: 5
control_low_ratio: -0.8
control_high_ratio: 1.25
control_m1_low: 0
control_m1_high: 180
control_shift_time_s: 0.02
control_direction_change_hold_ms: 50
control_m1_speed_deg_per_tick: 3
servo_count: 2
servo_1_name: 逗猫棒
servo_1_seg_count: 1
servo_1_idle_level: 0
servo_1_seg1_key: 0
servo_1_seg1_level: 128
servo_1_seg1_time_s: 0.5
servo_1_seg1_mode: hold
servo_1_seg2_key: 0
servo_1_seg2_level: 255
servo_1_seg2_time_s: 0.5
servo_1_seg2_mode: toggle
servo_2_name: 大灯
servo_2_seg_count: 2
servo_2_idle_level: 0
servo_2_seg1_key: 68
servo_2_seg1_level: 200
servo_2_seg1_time_s: 0.5
servo_2_seg1_mode: toggle
servo_2_seg2_key: 83
servo_2_seg2_level: 255
servo_2_seg2_time_s: 0.01
servo_2_seg2_mode: hold
servo_3_name: 伺服3
servo_3_seg_count: 2
servo_3_idle_level: 0
servo_3_seg1_key: 0
servo_3_seg1_level: 0
servo_3_seg1_time_s: 0.5
servo_3_seg1_mode: toggle
servo_3_seg2_key: 0
servo_3_seg2_level: 0
servo_3_seg2_time_s: 0.5
servo_3_seg2_mode: toggle
video_flip_h: false
video_flip_v: false
video_rotation: 180
auto_quality_enabled: true
auto_quality_low_rssi: -70
auto_quality_recover_rssi: -60
auto_quality_low_resolution: 1280x720 (HD)
auto_quality_low_quality: 60
auto_quality_low_fps: 30